### ISSUE TITLE
index.html missing in root directory

### ISSUE THREAD

**Issue by lguzzon** [jordwalke/reactapp#3]
Hi,
in README.md is specified that index.html is in the root dir (/) but I found it only in the resouce dir (/static_resources)
so?

**Comment by jordwalke** [comment]
Thanks - I'll be updating this project to be a very different architecture pretty soon. I didn't expect anyone to really follow this one yet (haven't announced it yet). The next version will still be a one-click app like this, but it will also give you connect middleware that you can integrate with your existing node.js server. It will also give you the power to render full html pages in react (so `/myfolder/index.html` will map to `/myfolder/index.jsx` which will render the full `<html><body>...`.

**Comment by xelius** [comment]
Bump. That new version sure sounds great, any news on this? I could really use a good boilerplate to get started with react, esp regarding the server rendering magic, best practices etc. Impatiently awaiting future awesomeness.

**Comment by jordwalke** [comment]
@xelius: Thanks for keeping on this. I'm absolutely working on it. I just want to get a solid implementation of sorcemaps working with it so that when you read the code in the browser, it's transformed properly, and when you get stack traces in server rendered mode, the line numbers are accurate. Hold tight!

**Comment by xelius** [comment]
@jordwalke, thats great to hear. Your good work is much appreciated - keep it up.

**Comment by jordwalke** [comment]
@xelius/@lguzzon: Thanks for being patient. I hope you'll be happy with this as a replacement (https://github.com/facebook/react-page).

Let me know if there's some features you'd like and I can help you guys get started. It should work with all the existing connect middleware out there (like less/sass/etc).
